export const size = {
  huge: 50,
  xxxtitle: 38,
  xxtitle: 36,
  xtitle: 34,
  title: 32,
  h1: 30,
  h2: 28,
  h3: 26,
  h4: 25,
  h5: 24,
  h6: 22,
  xxlarge: 20,
  xlarge: 19,
  large: 18,
  medium: 17,
  normal: 16,
  small: 15,
  xsmall: 14,
  xxsmall: 13,
  tiny: 12,
  xtiny: 11,
  xxtiny: 10,
  xxxtiny: 9,
};

export const family = {
  Poppins_ThinItalic: 'Poppins-ThinItalic',
  Poppins_Thin: 'Poppins-Thin',
  Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_MediumItalic: 'Poppins-MediumItalic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_LightItalic: 'Poppins-LightItalic',
  Poppins_Light: 'Poppins-Light',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  Poppins_ExtraBold: 'Poppins-ExtraBold',
  Poppins_BoldItalic: 'Poppins-BoldItalic',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_BlackItalic: 'Poppins-BlackItalic',
  Poppins_Black: 'Poppins-Black',
  //
  Montserrat_ThinItalic: 'Montserrat-ThinItalic',
  Montserrat_Thin: 'Montserrat-Thin',
  Montserrat_SemiBoldItalic: 'Montserrat-SemiBoldItalic',
  Montserrat_SemiBold: 'Montserrat-SemiBold',
  Montserrat_Regular: 'Montserrat-Regular',
  Montserrat_MediumItalic: 'Montserrat-MediumItalic',
  Montserrat_Medium: 'Montserrat-Medium',
  Montserrat_LightItalic: 'Montserrat-LightItalic',
  Montserrat_Light: 'Montserrat-Light',
  Montserrat_Italic: 'Montserrat-Italic',
  Montserrat_ExtraLightItalic: 'Montserrat-ExtraLightItalic',
  Montserrat_ExtraLight: 'Montserrat-ExtraLight',
  Montserrat_ExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
  Montserrat_ExtraBold: 'Montserrat_ExtraBold',
  Montserrat_BoldItalic: 'Montserrat-BoldItalic',
  Montserrat_Bold: 'Montserrat-Bold',
  Montserrat_BlackItalic: 'Montserrat-BlackItalic',
  Montserrat_Black: 'Montserrat-Black',
  
};
